package com.example.tuneguessrserver.response.websocket;

public enum MessageInfo {
    USER_SESSION,
    ROOM_SESSION,
    ROOM_CREATED,
    NEW_PLAYER_JOINED,
    JOINED_ROOM, PLAYER_LEFT, PLAYER_READY, GAME_START, NEXT_SONG, ERROR, ROOM_ERROR, GAME_ERROR, FINISHED, CORRECT_GUESS, WRONG_GUESS,

}
